service:
    port: 8181
spring:
  redis:
    host: 192.168.1.2
    port: 6379
    pool:
      max-idle: 10
      max-active: 10
      max-wait: 1000
  datasource:
    url: jdbc:mysql://192.168.1.2:3306/my-test?useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: Admin123!
  jpa:
    show-sql: true